### ISSUE TITLE
更多的可以买的东西的点子和一些建议

### ISSUE THREAD

**Issue by monicfenga** [liust97/rich-simulator#1]
单位都是元。以下所有商品都不一定要全部放进去。

#### 日常生活
* 辣条 - 0.5
* 维他柠檬茶 250ml - 2
* 茶叶蛋 - 自行定价
* 切糕 - 自行定价
* “塑料小人”（手办） - 自行定价
* 狗狗 * 大概5000
* 一株绿色植物 - 大约50-500
* 一罐上好的茶叶 - 自行定价（参考小罐茶的定价，但要乘以5，因为我们的罐比他们的大）

#### 科技产品
* 一台顶级配置的台式电脑 - 自行定价（可以使用网上的攒机工具获得价格）
* * Intel Xeon E7-8890 v4 - 70000
* * Intel 酷睿i9 9980XE - 16300
* * 机械键盘 - 自行定价（可以参考*静电容键盘*的价格）
* * 质量高的鼠标  - 自行定价
* * 数位板（可以画画，也可以用来玩游戏）  - 自行定价
* * RTX 2080显卡 - 5999（可加可不加）
* * 一块机械硬盘 - 自行定价
* 一台有1PB存储空间的服务器 - 自行定价（[参考LinusTechTips做过的一期视频](https://www.bilibili.com/video/av12303757)）
* MacBook Pro 16英寸 1TB版 - 22199
* iMac Pro- 38138
* Mac Pro - 41300（如果有国行就用国行售价）
* Apple Pro Display XDR - 41409
* * Pro Stand - 7017（这两个必须分开列，因为苹果就是这么干的）
* 微软 Surface Pro 7 （最贵的） - 17888
* 微软 Surface Book 2 （最贵的） - 23958
* 微软 Surface Studio 2（最贵的） - 38858
* 微软 HoloLens 2（仅设备） - 24601
* 无人机 - 自行定价（可加可不加）
* 哈苏 1亿像素单反相机 H6D-100c - 21万（一般的单反相机弱爆了）
* iPhone 11 Pro Max 512GB版 - 12699
* 小米MIX Alpha - 19999
* 三星Galaxy Fold - 15999
* 华为Mate X - 16999
* Kindle Oasis 3 - 2658
* 正版Adobe Creative Cloud（全套软件） - 大约6942
* 一整套HiFi设备 - 自行定价

#### 好玩的
* PlayStation 4 - 3210
* XBox One X - 1500
* Nintendo Switch - 1000
* 购买Steam上的每一款游戏（我记得有一个专门的网站统计价格，也有说“25万美元”的）
* 乐高积木 - 自行定价
* 拼装模型 - 自行定价
* 泡泡纸 - 1

#### 乐器
* 三角钢琴 - 大概上万元
* 架子鼓 - 自行定价
* 吉他 - 自行定价
* 小提琴 - 自行定价
* 古筝 - 自行定价
* Vocaloid，加上一套音色库 - 3200（我认为这个算乐器）
* 可酌情添加其他乐器。

#### 衣着打扮
* 洛丽塔裙 - 自行定价（为何不可呢？）
* 汉服 - 自行定价（为何不可呢？）
* 一套化妆品 - 自行定价（因为只有口红明显不够）

#### 其他
* 天文望远镜 - 自行定价
* 金条 - 自行定价
* 钻石 - 自行定价
* 奇石 - 自行定价
* 字画 - 自行定价
* 建造一座自己的雕像 - 5000000（较为平均的价格）

### 思考题：
答案可以放在页面中。

* 如果将这些钱全都用于手机充值的话，需要花多长时间才能花光？按照每天4通电话、全天开着流量并使用5GB的流量（不使用任何流量包）计算。资费可以参考自己使用的套餐资费。
* 如果每天都坐公交车或地铁4次的话，这些钱能花到什么时候？

### 建议

* 在网页中简单描述这个东西是个啥
* 右上角的“购物车”按钮在按下后可以变成“回到商城”按钮

**Comment by liust97** [comment]
谢谢建议，有心了！
很好的建议，未来有空会进行改进。

**Comment by liust97** [comment]
增加了建议的部分商品。（建议很好！不加太多是考虑到有些东西可能大部分人不太了解（还有我懒））
网页上增加了描述，改进了按钮。
